influxdb:
  url: http://192.168.88.186:8086
  token: yFyR1p7hKO6x593dTTgAJxjXAd43Oskh84sHBFNGpge7HK6IACyqsm2NXQuBk0eIfDf8FilT3jn4HUImICFF4w==
  org: kastankovi.cz
  bucket: homeassistant
tapo:
  email: kastanekdavid@gmail.com
  password: gQ0$zCN9F@5sdk
  plugs:
    - name: heater
      ip: 192.168.88.111
    - name: tuv
      ip: 192.168.88.117
thresholds:
  maxTemp: 67 # max temperature to which water is heated
  maxLoad: 3300 # max power per electrical phase
  minTuvSoC: 40 # min SoC percentage for water to start being heated
  minPanels: 2000 # min power available from solar panels
  maxSoC: 100 # max percentage value for SoC
  maxSoCNil: 0 # max value for SoC when metric not available
  loadIdle: 1000 # max active power on electrical phase for that phase to be considered available for more load
  minHeaterSoC: 60 # min SoC percentage for power being considered to be sent to the air heater
  panels1Idle: 510 # min voltage on string 1 for panels to be idle when sun is shining
  panels1Min: 300 # min voltage on string 1 for panels when sun is shining
